// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddPassword(arg1:string):Promise<boolean>;

export function GeneratePassword():Promise<string>;

export interface Category {
  Name: string;
  Icon: string;
  Color: string;
}

export function GetPasswordCategories():Promise<Category[]>;

export function GetPasswordsByCategory(arg1:string):Promise<string>;

export function GetSettings():Promise<string>;

export function Login(arg1:string,arg2:string):Promise<boolean>;

export function UpdateSettings(arg1:string,arg2:string):Promise<boolean>;
