// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddPassword(arg1:main.Password):Promise<boolean>;

export function GeneratePassword():Promise<string>;

export function GetPasswordCategories():Promise<Array<main.Category>>;

export function GetPasswordsByCategory(arg1:string):Promise<Array<main.Password>>;

export function GetRealmHealth():Promise<number>;

export function GetSettings():Promise<string>;

export function Login(arg1:string,arg2:string):Promise<boolean>;

export function UpdateSettings(arg1:string,arg2:string):Promise<boolean>;
