// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddPassword(arg1) {
  return window['go']['main']['App']['AddPassword'](arg1);
}

export function GeneratePassword() {
  return window['go']['main']['App']['GeneratePassword']();
}

export function GetPasswordCategories() {
  return window['go']['main']['App']['GetPasswordCategories']();
}

export function GetPasswordsByCategory(arg1) {
  return window['go']['main']['App']['GetPasswordsByCategory'](arg1);
}

export function GetRealmHealth() {
  return window['go']['main']['App']['GetRealmHealth']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function Login(arg1, arg2) {
  return window['go']['main']['App']['Login'](arg1, arg2);
}

export function UpdateSettings(arg1, arg2) {
  return window['go']['main']['App']['UpdateSettings'](arg1, arg2);
}
