# GoReleaser 配置文件
# 用于自动化构建和发布多个平台版本

version: 2

# 项目名称
project_name: realm

# 发布配置
release:
  # GitHub发布配置
  github:
    owner: panyingyun  # 修改为你的GitHub用户名
    name: realm     # 修改为你的仓库名
  
  # 发布模式：替换或跳过已存在的发布
  mode: replace
  
  # 发布前执行的命令（可选）
  # prerelease: auto  # 自动检测是否为预发布版本
  
  # 发布说明模板
  header: |
    ## {{ .ProjectName }} {{ .Tag }}
    
    发布版本 {{ .Tag }}
    
  footer: |
    ---
    
    由 [GoReleaser](https://github.com/goreleaser/goreleaser) 自动生成

# 构建前钩子 - 构建前端资源
before:
  hooks:
    - go mod tidy
    - npm --prefix frontend install
    - npm --prefix frontend run build

# 构建配置 - 支持多个平台和架构
builds:
  - id: default
    # 主程序入口
    main: .
    
    # 二进制文件名称
    # Windows 平台会自动添加 .exe 扩展名
    binary: realm
    
    # 构建平台 - Linux、Windows、Mac 的 amd64 版本
    goos:
      - linux
      - windows
      - darwin
    
    # 架构 - amd64
    goarch:
      - amd64
    
    # 环境变量
    # 注意：Wails 项目通常需要 CGO，但跨平台构建时可能需要禁用
    env:
      - CGO_ENABLED=0
    
    # 构建标志
    flags:
      - -trimpath
    
    # LDFlags
    ldflags:
      - -s -w
      - -X main.Version={{.Version}}
      - -X main.GitCommit={{.Commit}}
      - -X main.BuildTime={{.Date}}
    
    # 忽略不需要的平台和架构组合
    ignore:
      - goos: windows
        goarch: arm
      - goos: windows
        goarch: arm64
      - goos: linux
        goarch: arm
      - goos: linux
        goarch: arm64
      - goos: darwin
        goarch: arm
      - goos: darwin
        goarch: arm64
      - goos: freebsd
      - goos: openbsd
      - goos: netbsd

# 归档配置
archives:
  - id: default
    # 文件名模板
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    
    # 包含的文件
    files:
      - LICENSE
      - README.md

# 校验和配置
checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_checksums.txt"
  algorithm: sha256

# 快照配置（用于测试）
snapshot: {}

# Changelog配置
changelog:
  # 使用git日志生成changelog
  use: git
  # 过滤提交信息
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - "^update:"
