# GoReleaser 配置文件
# 用于自动化构建和发布多个平台版本

version: 2

# 项目名称
project_name: realm

# 发布配置
release:
  # GitHub发布配置
  github:
    owner: panyingyun  # 修改为你的GitHub用户名
    name: realm     # 修改为你的仓库名
  
  # 发布模式：替换或跳过已存在的发布
  mode: replace
  
  # 发布前执行的命令（可选）
  # prerelease: auto  # 自动检测是否为预发布版本
  
  # 发布说明模板
  header: |
    ## {{ .ProjectName }} {{ .Tag }}
    
    发布版本 {{ .Tag }}
    
  footer: |
    ---
    
    由 [GoReleaser](https://github.com/goreleaser/goreleaser) 自动生成

# 构建前钩子 - 构建前端资源和 Wails 应用
before:
  hooks:
    - go mod tidy
    - npm --prefix frontend install
    - npm --prefix frontend run build
    # 注意：Wails 应用需要使用 wails build 命令
    # 但由于 GoReleaser 使用 go build，我们需要确保构建标签正确传递

# 构建配置 - 支持多个平台和架构
builds:
  # Linux 构建配置 - Ubuntu 24.04（需要 webkit2_41 标签）
  - id: linux-webkit2_41
    # 主程序入口
    main: .
    
    # 二进制文件名称
    binary: realm
    
    # 构建平台
    goos:
      - linux
    
    # 架构
    goarch:
      - amd64
    
    # 环境变量 - Linux 平台需要 CGO（Wails 需要）
    env:
      - CGO_ENABLED=1
    
    # 构建标志
    flags:
      - -trimpath
    
    # 构建标签 - Ubuntu 24.04 使用 webkit2_41
    tags:
      - webkit2_41
    
    # LDFlags
    ldflags:
      - -s -w
      - -X main.Version={{.Version}}
      - -X main.GitCommit={{.Commit}}
      - -X main.BuildTime={{.Date}}
  
  # Linux 构建配置 - Ubuntu 22.04（需要 webkit2_40 标签）
  - id: linux-webkit2_40
    # 主程序入口
    main: .
    
    # 二进制文件名称
    binary: realm
    
    # 构建平台
    goos:
      - linux
    
    # 架构
    goarch:
      - amd64
    
    # 环境变量 - Linux 平台需要 CGO（Wails 需要）
    env:
      - CGO_ENABLED=1
    
    # 构建标志
    flags:
      - -trimpath
    
    # 构建标签 - Ubuntu 22.04 使用 webkit2_40
    tags:
      - webkit2_40 
      - desktop,production

    # LDFlags
    ldflags:
      - -s -w
      - -X main.Version={{.Version}}
      - -X main.GitCommit={{.Commit}}
      - -X main.BuildTime={{.Date}}
  
  # Windows 构建配置
  - id: windows
    main: .
    binary: realm
    goos:
      - windows
    goarch:
      - amd64
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    # 构建标签 
    tags:
      - webkit2_40 
      - desktop,production
    ldflags:
      - -s -w 
      - -H windowsgui
      - -X main.Version={{.Version}}
      - -X main.GitCommit={{.Commit}}
      - -X main.BuildTime={{.Date}}
  
  # macOS 构建配置
  - id: darwin
    main: .
    binary: realm
    goos:
      - darwin
    goarch:
      - amd64
    # 环境变量 - Linux 平台需要 CGO（Wails 需要）
    env:
      - CGO_ENABLED=1
    flags:
      - -trimpath
    # 构建标签
    tags:
      - webkit2_40 
      - desktop,production
    ldflags:
      - -s -w
      - -X main.Version={{.Version}}
      - -X main.GitCommit={{.Commit}}
      - -X main.BuildTime={{.Date}}

# 归档配置
archives:
  # Ubuntu 24.04 归档配置（webkit2_41）
  - id: linux-webkit2_41
    builds:
      - linux-webkit2_41
    # 文件名模板 - 包含 webkit 版本信息
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}_webkit2_41"
    formats:
      - tar.gz
    # 包含的文件
    files:
      - LICENSE
      - README.md
  
  # Ubuntu 22.04 归档配置（webkit2_40）
  - id: linux-webkit2_40
    builds:
      - linux-webkit2_40
    # 文件名模板 - 包含 webkit 版本信息
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}_webkit2_40"
    formats:
      - tar.gz
    # 包含的文件
    files:
      - LICENSE
      - README.md
  
  # Windows 归档配置
  - id: windows
    builds:
      - windows
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    formats:
      - zip
    files:
      - LICENSE
      - README.md
  
  # macOS 归档配置
  - id: darwin
    builds:
      - darwin
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    formats:
      - tar.gz
    files:
      - LICENSE
      - README.md

# 校验和配置
checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_checksums.txt"
  algorithm: sha256

# 快照配置（用于测试）
snapshot: {}

# Changelog配置
changelog:
  # 使用git日志生成changelog
  use: git
  # 过滤提交信息
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - "^update:"
